from pathlib import Path
import re
p=Path('/home/ubuntu/travora/client/src/App.tsx')
s=p.read_text()
approvals='''function Approvals({ history = false }: { history?: boolean }) {
  const { journeys, loading, error } = useTravelRequests();
  const [working, setWorking] = useState<string | null>(null);
  const user = getStoredUser<AuthUser>();
  async function decide(journey: Journey, action: "approve" | "reject") { setWorking(`${action}-${journey.id}`); try { const approver = user?.username || "authenticated approver"; if (action === "approve") await travelRequestsApi.approve(journey.id, approver); else await travelRequestsApi.reject(journey.id, approver, "Rejected from Travora approval workspace."); toast.success(`Request ${action === "approve" ? "approved" : "rejected"}.`); window.location.reload(); } catch (decisionError) { toast.error(decisionError instanceof Error ? decisionError.message : "Decision could not be saved."); } finally { setWorking(null); } }
  const rows = history ? journeys.filter((journey) => journey.status !== "Pending approval") : journeys.filter((journey) => journey.status === "Pending approval");
  return <div className="page-stack animate-page"><PageTitle meta={pageMeta[history ? "/approver/history" : "/approver"]} /><div className="summary-strip"><div><span className="card-kicker">{history ? "DECISION LOG" : "NEEDS YOUR REVIEW"}</span><strong>{String(rows.length).padStart(2, "0")}</strong><span>{history ? "decisions recorded" : "requests waiting"}</span></div><div className="strip-icon"><FileCheck2 size={22} /></div></div><div className="panel table-panel"><div className="section-title-row"><div><span className="card-kicker">{history ? "BACKEND HISTORY" : "PENDING REQUESTS"}</span><h2 className="section-heading">{history ? "Recent approval activity" : "Requests ready for review"}</h2></div><span className="data-note"><ShieldCheck size={13} /> Live backend data</span></div>{error && <div className="form-error-message"><XCircle size={15} />{error}</div>}{loading ? <EmptyState icon={<Clock3 size={20} />} title="Loading approvals" description="Fetching requests from Travora." /> : rows.length ? <div className="approval-list">{rows.map((request) => <div className="approval-item" key={request.id}><div className="approval-identity"><div className="avatar">{request.destination.slice(0, 2).toUpperCase()}</div><div><strong>{request.destination}</strong><span>{request.id} · {request.project}</span></div></div><div className="approval-route"><strong>{request.from} → {request.to}</strong><span>{request.dates} · {request.tripType}</span></div><div className="approval-amount"><span>Status</span><StatusBadge status={request.status} /></div>{history ? <StatusBadge status={request.status} /> : <div className="approval-actions"><button className="button button-small button-ghost" disabled={working !== null} onClick={() => decide(request, "reject")}>{working === `reject-${request.id}` ? "Saving…" : "Reject"}</button><button className="button button-small button-primary" disabled={working !== null} onClick={() => decide(request, "approve")}>{working === `approve-${request.id}` ? "Saving…" : "Approve"}</button></div>}</div>)}</div> : <EmptyState icon={<FileCheck2 size={20} />} title={history ? "No decisions yet" : "No requests waiting"} description={history ? "Completed approval decisions will appear here." : "New pending requests will appear here when submitted."} />}</div></div>;
}'''
s=re.sub(r'function Approvals\(\{ history = false \}: \{ history\?: boolean \}\) \{.*?\nfunction ConfirmDialog', approvals+'\nfunction ConfirmDialog', s, flags=re.S)
desk='''function TravelDesk() {
  const { journeys, loading, error } = useTravelRequests();
  const rows = journeys.filter((journey) => journey.status === "Approved" || journey.status === "Booked");
  return <div className="page-stack animate-page"><PageTitle meta={pageMeta["/travel-desk"]} /><section className="ops-hero"><div><span className="card-kicker">TODAY IN OPERATIONS</span><h2>Keep the journey moving.</h2><p>Approved journeys returned by the backend are ready for booking action.</p><Link href="/travel-desk/bookings" className="button button-primary">Open booking queue <ArrowUpRight size={16} /></Link></div><div className="ops-hero-metric"><span>Open work</span><strong>{String(rows.filter((row) => row.status === "Approved").length).padStart(2, "0")}</strong><small>approved trips</small></div></section><div className="stats-grid desk-stats"><StatCard label="Approved to book" value={String(rows.filter((row) => row.status === "Approved").length).padStart(2, "0")} detail="Live queue" icon={<Clock3 size={18} />} accent="stat-accent" /><StatCard label="Booked" value={String(rows.filter((row) => row.status === "Booked").length).padStart(2, "0")} detail="Live backend data" icon={<TicketCheck size={18} />} /><StatCard label="Cancellations" value={String(journeys.filter((row) => row.status === "Cancelled").length).padStart(2, "0")} detail="Current status" icon={<XCircle size={18} />} /></div><div className="panel table-panel"><div className="section-title-row"><div><span className="card-kicker">OPERATIONS QUEUE</span><h2 className="section-heading">Approved travel requests</h2></div><span className="data-note"><ShieldCheck size={13} /> Live backend data</span></div>{error && <div className="form-error-message"><XCircle size={15} />{error}</div>}{loading ? <EmptyState icon={<Clock3 size={20} />} title="Loading queue" description="Fetching approved requests from Travora." /> : rows.length ? <div className="responsive-table"><table><thead><tr><th>Journey</th><th>Route</th><th>Travel dates</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="table-journey"><span className="avatar avatar-tiny">{row.destination.slice(0, 2).toUpperCase()}</span><span><strong>{row.destination}</strong><small>{row.id} · {row.project}</small></span></div></td><td>{row.from} → {row.to}</td><td>{row.dates}</td><td><StatusBadge status={row.status === "Approved" ? "Booking pending" : row.status} /></td><td><button className="table-action" onClick={() => toast("Booking creation is available through the connected /api/bookings endpoint.")}>{row.status === "Approved" ? "Add booking" : "View ticket"} <ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div> : <EmptyState icon={<TicketCheck size={20} />} title="No approved journeys" description="Approved travel requests will appear here for ticketing." />}</div></div>;
}'''
s=re.sub(r'function TravelDesk\(\) \{.*?\nfunction Reports', desk+'\nfunction Reports', s, flags=re.S)
p.write_text(s)
