from pathlib import Path
import re

p = Path('/home/ubuntu/travora/client/src/App.tsx')
s = p.read_text()
s = s.replace('travelRequestsApi, type AuthUser', 'travelRequestsApi, dashboardApi, employeesApi, bookingsApi, type AuthUser')

reports = '''function Reports() {
  const { journeys, loading } = useTravelRequests();
  const counts = { approved: journeys.filter((j) => j.status === "Approved").length, pending: journeys.filter((j) => j.status === "Pending approval").length, completed: journeys.filter((j) => j.status === "Completed").length };
  const destinations = Array.from(new Set(journeys.map((j) => j.destination))).slice(0, 4);
  return <div className="page-stack animate-page"><PageTitle meta={pageMeta["/employee/reports"]} /><div className="report-header"><div><span className="card-kicker">LIVE TRAVEL DATA</span><h2>Patterns that help you plan ahead.</h2><p>These signals are calculated from the travel requests returned for your authenticated account.</p></div><div className="report-period"><CalendarDays size={16} /> Current account</div></div><section className="stats-grid"><StatCard label="Total requests" value={String(journeys.length).padStart(2, "0")} detail={loading ? "Loading" : "From backend"} icon={<FileText size={18} />} /><StatCard label="Approved" value={String(counts.approved).padStart(2, "0")} detail="Current status" icon={<Check size={18} />} accent="stat-accent" /><StatCard label="Pending" value={String(counts.pending).padStart(2, "0")} detail="Needs approval" icon={<Clock3 size={18} />} /><StatCard label="Completed" value={String(counts.completed).padStart(2, "0")} detail="Current status" icon={<Compass size={18} />} /></section><section className="report-grid"><div className="panel destination-panel"><div className="section-title-row"><div><span className="card-kicker">DESTINATIONS</span><h2 className="section-heading">Where work takes you</h2></div><Compass size={18} className="panel-icon" /></div>{destinations.length ? <div className="destination-list">{destinations.map((destination, index) => <Destination key={destination} name={destination} count={`${journeys.filter((j) => j.destination === destination).length} request${journeys.filter((j) => j.destination === destination).length === 1 ? "" : "s"}`} width={`${86 - index * 17}%`} />)}</div> : <EmptyState icon={<Compass size={20} />} title="No destination data yet" description="Submit a travel request to build your report." />}</div><div className="panel insight-card"><div className="insight-symbol"><Sparkles size={18} /></div><div><span className="card-kicker">TRAVORA SIGNAL</span><h3>{loading ? "Loading your travel signal" : journeys.length ? "Keep the request context close." : "Your first request starts the signal."}</h3><p>{loading ? "Fetching the latest request activity." : journeys.length ? "Approval and booking teams can use the same request record to keep the handoff clear." : "Create a request to see destinations, statuses and travel patterns here."}</p></div></div></section></div>;
}'''
s = re.sub(r'function Reports\(\) \{.*?\nfunction Destination', reports + '\nfunction Destination', s, flags=re.S)

admin = '''function Admin({ section = "overview" }: { section?: string }) {
  const [summary, setSummary] = useState<Record<string, number> | null>(null);
  const [employees, setEmployees] = useState<Array<Record<string, string>>>([]);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([dashboardApi.summary(), employeesApi.list()]).then(([nextSummary, nextEmployees]) => { setSummary(nextSummary as Record<string, number>); setEmployees(Array.isArray(nextEmployees) ? nextEmployees as Array<Record<string, string>> : []); }).catch((requestError) => setError(requestError instanceof Error ? requestError.message : "Admin data is unavailable.")); }, []);
  const title = section === "employees" ? "People directory" : section === "requests" ? "Request activity" : section === "bookings" ? "Booking activity" : section === "reports" ? "Organization signals" : "Control center";
  return <div className="page-stack animate-page"><PageTitle meta={{ ...pageMeta[section === "overview" ? "/admin" : `/admin/${section}`], title }} /><section className="admin-hero"><div><span className="card-kicker">ORGANIZATION VIEW</span><h2>Travel, with the bigger picture in view.</h2><p>Monitor people, requests and bookings from the authenticated admin workspace.</p></div><div className="admin-orbit"><ShieldCheck size={22} /><span>Policy-aware workspace</span></div></section>{error && <div className="form-error-message"><XCircle size={15} />{error}</div>}<section className="stats-grid"><StatCard label="Active employees" value={String(employees.length || 0)} detail="From backend" icon={<UsersRound size={18} />} /><StatCard label="Open requests" value={String(summary?.pendingRequests || 0)} detail="Pending" icon={<FileText size={18} />} accent="stat-accent" /><StatCard label="Total bookings" value={String(summary?.totalBookings || 0)} detail="From backend" icon={<TicketCheck size={18} />} /><StatCard label="Travel requests" value={String(summary?.totalTravelRequests || 0)} detail="All statuses" icon={<WalletCards size={18} />} /></section><div className="panel table-panel"><div className="section-title-row"><div><span className="card-kicker">{section === "employees" ? "DIRECTORY" : "LATEST ACTIVITY"}</span><h2 className="section-heading">{section === "employees" ? "Employees" : "Backend summary"}</h2></div></div>{employees.length ? <div className="responsive-table"><table><thead><tr><th>Name</th><th>Department</th><th>Designation</th><th>Employee ID</th><th /></tr></thead><tbody>{employees.map((employee, index) => <tr key={employee.id || employee.employeeId || index}><td><div className="table-journey"><span className="avatar avatar-tiny">{String(employee.name || "E").slice(0, 2).toUpperCase()}</span><span><strong>{employee.name || "Unnamed employee"}</strong><small>{employee.employeeId || "—"}</small></span></div></td><td>{employee.department || "—"}</td><td>{employee.designation || "—"}</td><td>{employee.employeeId || "—"}</td><td><ChevronRight size={16} className="row-chevron" /></td></tr>)}</tbody></table></div> : <EmptyState icon={<UsersRound size={20} />} title="No employee data returned" description="The admin directory will populate from the connected backend." />}</div></div>;
}'''
s = re.sub(r'function Admin\(\{ section = "overview" \}: \{ section\?: string \}\) \{.*?\nfunction Login', admin + '\nfunction Login', s, flags=re.S)
p.write_text(s)
