spring.application.name=traveldesk-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/traveldesk
spring.datasource.username=haripreeth
spring.datasource.password=sumiksha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.debug=true
logging.level.org.springframework.security=DEBUG
