server.port=${PORT:8080}
spring.application.name=traveldesk-backend

spring.datasource.url=${TRAVORA_DB_URL:jdbc:postgresql://localhost:5432/traveldesk}

spring.datasource.username=${TRAVORA_DB_USERNAME:}

spring.datasource.password=${TRAVORA_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=${TRAVORA_JPA_SHOW_SQL:false}

app.jwt.secret=${TRAVORA_JWT_SECRET:}
app.cors.allowed-origins=${TRAVORA_CORS_ALLOWED_ORIGINS:http://localhost:3000}

spring.security.debug=${TRAVORA_SECURITY_DEBUG:false}

logging.level.org.springframework.security=${TRAVORA_SECURITY_LOG_LEVEL:INFO}
logging.level.org.springframework.web=${TRAVORA_WEB_LOG_LEVEL:INFO}
logging.level.com.traveldesk.backend=${TRAVORA_APP_LOG_LEVEL:INFO}
